import { useMemo, useState } from 'react';
import { Sparkles, ShieldCheck, ShieldAlert, ChevronRight } from 'lucide-react';
import type { AccountDetail, DeltaCard, DeltaMetric, Finding } from '@/api/types';
import { Card, Badge, SeverityPill, Segmented, cx } from '@/components/ui';
import { useEvidence } from '@/components/evidence';
import { usd, pct, fmtDate, ACTION_LABEL } from '@/lib/format';
import { CitedText, DispositionControl, flagDot, flagTone, SectionLabel } from '../common';
import { FAMILY_LABEL } from '../common/families';
import { Info } from '@/help/Info';

export default function OverviewTab({ a }: { a: AccountDetail }) {
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4">
        {a.deltas.map((d, i) => <DeltaCardView key={d.key} d={d} findings={a.findings} info={i === 0} />)}
      </div>
      <div className="grid grid-cols-12 gap-4">
        <NarrativePanel a={a} className="col-span-12 xl:col-span-8" />
        <ActionsPanel a={a} className="col-span-12 xl:col-span-4" />
      </div>
      <FindingsTable findings={a.findings} />
    </div>
  );
}

const STATUS_STYLE: Record<DeltaCard['status'], string> = { ACTION: 'bg-crit', WATCH: 'bg-med', OK: 'bg-ok' };
function DeltaCardView({ d, findings, info }: { d: DeltaCard; findings: Finding[]; info?: boolean }) {
  const ev = useEvidence();
  const open = (m: DeltaMetric) => {
    const f = m.finding_ids?.map((id) => findings.find((x) => x.finding_id === id)).find(Boolean);
    if (f) ev.openFinding(f); else if (m.obs_ids?.[0]) ev.openObs(m.obs_ids[0]);
  };
  return (
    <section className="relative overflow-hidden rounded-[var(--radius-card)] border border-line bg-surface shadow-[var(--shadow-card)]">
      <div className={cx('absolute inset-y-0 left-0 w-[3px]', STATUS_STYLE[d.status])} />
      <div className="px-3.5 pb-1 pt-2.5">
        <div className="flex items-center justify-between">
          <span className="inline-flex items-center gap-1.5 text-[11px] font-medium uppercase tracking-[.05em] text-ink-500">{d.title}{info && <Info id="account.deltas" className="normal-case" />}</span>
          <Badge tone={d.status === 'ACTION' ? 'crit' : d.status === 'WATCH' ? 'med' : 'ok'}>{d.status === 'ACTION' ? 'Action' : d.status === 'WATCH' ? 'Watch' : 'OK'}</Badge>
        </div>
        <div className="mt-1 text-[13px] font-semibold leading-snug text-ink-950">{d.headline}</div>
      </div>
      <div className="px-2 pb-2">
        {d.metrics.map((m, i) => {
          const clickable = !!(m.finding_ids?.length || m.obs_ids?.length);
          return (
            <button key={i} disabled={!clickable} onClick={() => open(m)} title={m.note}
              className={cx('grid w-full grid-cols-[8px_1fr_auto] items-baseline gap-2 rounded-md px-1.5 py-[5px] text-left', clickable && 'hover:bg-ink-50')}>
              <span className={cx('size-1.5 translate-y-[-1px] rounded-full', flagDot(m.flag))} />
              <span className="min-w-0">
                <span className="block truncate text-[12px] text-ink-600">{m.label}</span>
                {(m.before || m.after) && <span className="num block truncate text-[11px] text-ink-400">{m.before ?? ''}{m.before && m.after ? ' → ' : ''}{m.after ?? ''}</span>}
                {m.note && <span className="block truncate text-[11px] text-ink-400">{m.note}</span>}
              </span>
              <span className={cx('num text-[13px] font-semibold', flagTone(m.flag), clickable && 'underline decoration-dotted decoration-accent-500/50 underline-offset-[3px]')}>{m.display}</span>
            </button>
          );
        })}
      </div>
    </section>
  );
}

function NarrativePanel({ a, className }: { a: AccountDetail; className?: string }) {
  const n = a.narrative;
  return (
    <Card className={className} title={<span className="flex items-center gap-2"><Sparkles className="size-3.5 text-accent-600" />Why this account needs attention<Info id="account.narrative" /></span>}
      actions={<div className="flex items-center gap-1.5 text-[11px] text-ink-500">
        <Badge tone={n.generated_by === 'llm' ? 'accent' : 'neutral'}>generated by {n.generated_by}{n.model ? ` · ${n.model}` : ''}</Badge>
        {n.critique && <Badge tone={n.critique.challenged ? 'med' : 'ok'} title={n.critique.summary}>{n.critique.challenged ? <ShieldAlert className="size-3" /> : <ShieldCheck className="size-3" />}critique {n.critique.upheld} upheld · {n.critique.challenged} challenged</Badge>}
      </div>}>
      <CitedText text={n.text} findings={a.findings} />
      {n.critique && <div className="mt-3 border-t border-line pt-2 text-[11.5px] text-ink-500">Critique pass: {n.critique.summary}. Every sentence cites a finding (F) or an observation (O); uncited sentences are removed before display.</div>}
    </Card>
  );
}

function ActionsPanel({ a, className }: { a: AccountDetail; className?: string }) {
  const ev = useEvidence();
  return (
    <Card className={className} title={<span className="inline-flex items-center gap-1.5">Actions<Info id="account.actions" /></span>} subtitle="Proposed by the engine — underwriter decides" pad={false}>
      <div className="divide-y divide-line">
        {a.actions.map((x) => (
          <div key={x.action_id} className="px-4 py-2.5">
            <div className="flex items-center justify-between gap-2">
              <span className="text-[13px] font-medium text-ink-900">{x.title}</span>
              <span className="num text-[12px] font-semibold text-ink-900">{x.impact_usd ? usd(x.impact_usd) : ''}</span>
            </div>
            <div className="mt-0.5 flex flex-wrap items-center gap-x-2 text-[11px] text-ink-500">
              <Badge>{ACTION_LABEL[x.type]}</Badge><span>{x.owner}</span><span className="num">due {fmtDate(x.due)}</span><span className="lowercase">{x.status.replace('_', ' ')}</span>
            </div>
            {x.finding_ids.length > 0 && (
              <div className="mt-1 flex flex-wrap gap-1">
                {x.finding_ids.map((id) => { const f = a.findings.find((y) => y.finding_id === id); return f ? <button key={id} onClick={() => ev.openFinding(f)} className="max-w-full truncate rounded bg-ink-50 px-1.5 text-left text-[11px] text-ink-600 hover:bg-accent-50 hover:text-accent-700">{f.title}</button> : null; })}
              </div>
            )}
          </div>
        ))}
        {a.actions.length === 0 && <div className="px-4 py-6 text-center text-[12px] text-ink-500">No actions — Pass 1 has not run.</div>}
      </div>
    </Card>
  );
}

export function FindingsTable({ findings }: { findings: Finding[] }) {
  const ev = useEvidence();
  const [filter, setFilter] = useState<'open' | 'all' | 'material'>('all');
  const shown = findings.filter((f) => filter === 'all' || (filter === 'open' ? f.status === 'OPEN' : f.material));
  const groups = useMemo(() => {
    const m = new Map<string, Finding[]>();
    shown.forEach((f) => m.set(f.family, [...(m.get(f.family) ?? []), f]));
    return [...m.entries()].sort((x, y) => y[1].reduce((s, f) => s + f.impact_usd, 0) - x[1].reduce((s, f) => s + f.impact_usd, 0));
  }, [shown]);
  const accepted = findings.filter((f) => f.status === 'ACCEPTED').length, rejected = findings.filter((f) => f.status === 'REJECTED').length;
  return (
    <Card pad={false} title={<span className="inline-flex items-center gap-1.5">{`Findings (${findings.length})`}<Info id="account.findings" /></span>} subtitle={`${findings.filter((f) => f.status === 'OPEN').length} open · ${accepted} accepted · ${rejected} rejected · every disposition needs a reason code`}
      actions={<Segmented value={filter} onChange={setFilter} options={[{ key: 'all', label: 'All' }, { key: 'open', label: 'Open' }, { key: 'material', label: 'Material' }]} />}>
      <div className="overflow-x-auto">
        <table className="dt min-w-[1100px]">
          <thead><tr><th>Severity</th><th>Finding</th><th>Observed</th><th>Expected</th><th className="r">$ impact</th><th className="r">Conf.</th><th>Pass</th><th>Status</th><th className="r">Disposition</th></tr></thead>
          {groups.map(([fam, fs]) => (
            <tbody key={fam}>
              <tr><td colSpan={9} className="!bg-ink-50/60 !py-1.5"><SectionLabel right={<span className="num text-[11px] text-ink-500">{usd(fs.reduce((s, f) => s + f.impact_usd, 0))}</span>}>{FAMILY_LABEL[fam] ?? fam} · {fs.length}</SectionLabel></td></tr>
              {fs.map((f) => (
                <tr key={f.finding_id} className={cx('cursor-pointer', (f.status === 'REJECTED' || f.status === 'RESOLVED') && 'opacity-55')} onClick={() => ev.openFinding(f)}>
                  <td><SeverityPill s={f.severity} /></td>
                  <td className="max-w-[340px]">
                    <div className="flex items-center gap-1 font-medium text-ink-900">{f.title}<ChevronRight className="size-3 shrink-0 text-ink-300" /></div>
                    <div className="mono truncate text-[10.5px] text-ink-400">{f.rule_id} v{f.rule_version} · {f.subject_label}{f.critique?.verdict === 'CHALLENGED' && <span className="ml-1 font-sans text-med">· critique challenged</span>}</div>
                  </td>
                  <td className="max-w-[240px] text-[12px] text-ink-700">{f.observed}</td>
                  <td className="max-w-[200px] text-[12px] text-ink-500">{f.expected}</td>
                  <td className="num r font-semibold">{f.impact_usd ? usd(f.impact_usd) : '—'}<div className="max-w-[140px] truncate text-[10.5px] font-normal text-ink-400" title={f.impact_method}>{f.impact_method}</div></td>
                  <td className="num r text-ink-600">{pct(f.confidence, 0)}</td>
                  <td className="num text-ink-500">P{f.pass}</td>
                  <td><Badge tone={f.status === 'OPEN' ? 'high' : f.status === 'ACCEPTED' ? 'ok' : f.status === 'REJECTED' ? 'neutral' : f.status === 'DEFERRED' ? 'med' : 'info'}>{f.status.toLowerCase()}</Badge></td>
                  <td className="r"><DispositionControl f={f} /></td>
                </tr>
              ))}
            </tbody>
          ))}
        </table>
        {findings.length === 0 && <div className="py-8 text-center text-[13px] text-ink-500">No findings.</div>}
      </div>
    </Card>
  );
}
