"""Workflow playbook definitions: complete, real-life renewal flows from broker submission to an
issued (or non-renewed) policy. Each step says what a presenter would say; numbers are never
written here — the engine's live result for the step is read out after it runs.

Each playbook also carries a client brief: who it is for, the business problem, what happens,
what is the real product versus a stand-in, what to point at, and the value it demonstrates.
"""
from __future__ import annotations


def S(code: str, label: str, action: str = "view", say: str = "", **params) -> dict:
    return {"code": code, "label": label, "action": action, "say": say or label, "params": params}


REAL_CORE = ["Evidence ledger and document extraction (the files are parsed, not pre-loaded)", "Location matching across years", "Control rules and findings",
             "Three-run RARC split and technical price", "Authority matrix and terms-hash approvals", "Contract comparison quote ↔ binder ↔ policy"]
MOCK_CORE = ["Broker (replies by rule: accepts at or near target/technical, otherwise counters; returns requested documents after 3 days)",
             "Carrier rater and CAT model (deterministic stand-ins with the same inputs and outputs)", "Policy admin system (issues the policy; can inject a keying error)",
             "Clearance service, engineering system, billing"]

PLAYBOOKS: list[dict] = [
    # ------------------------------------------------------------------------------------------------ S2
    {"id": "reprice-refer", "account_id": "acc_s2", "title": "Full renewal — reprice, refer, bind, catch and correct an issuance error",
     "aspects": ["Submission intake", "RARC split", "Authority", "Subjectivities", "Contract integrity", "Corrective endorsement"],
     "intro": "This is ABC Manufacturing, a five-location manufacturer renewing on the first of November. I'll take it from the broker's email to an issued, corrected policy, "
              "and show exactly where a conventional renewal would have leaked margin.",
     "outro": "One renewal, end to end. Price corrected, terms tightened, authority enforced, the issuance error fixed by endorsement, and every step evidenced.",
     "brief": {
         "audience": "Chief underwriting officer, head of property, pricing and underwriting operations",
         "problem": "Renewals that look like rate increases are often rate cuts once exposure growth is removed. Referral approvals drift from the terms actually bound, and issuance errors sit undetected until a claim.",
         "story": ["Broker emails the renewal SOV; it is parsed cell by cell and matched to last year's schedule.",
                   "A new coastal location and an occupancy change are found; the rater and CAT model are rerun three times to split the premium change into exposure, terms and pure rate.",
                   "The underwriter accepts the findings, quotes on guideline terms, and the quote is referred because it is above their authority.",
                   "The approver adds a condition; it becomes a subjectivity printed on the binder.",
                   "The broker accepts; the platform binds, the mock policy system mis-keys a deductible, the platform catches it and issues a corrective endorsement.",
                   "The broker sends the outstanding document; the subjectivity clears."],
         "watch": ["Stage 06: the three rater runs and the RARC split (broker's headline change vs like-for-like)",
                   "Stage 07: the approval is tied to a hash of the exact terms", "Stage 10: subjectivities on the binder",
                   "Stage 11: binder ↔ policy diff and the corrective endorsement"],
         "value": "Rate adequacy restored on an under-priced account, and a contract error fixed before any claim.",
         "questions": ["How many of your renewals would show a different RARC like-for-like?", "Who checks the issued policy against the binder today, and when?"]},
     "steps": [
         S("01", "Broker's renewal submission arrives", "advance_submission",
           "The broker's renewal email lands with the statement of values attached. It's ingested automatically; nobody rekeys a thing."),
         S("02", "Clearance: duplicates, licence, sanctions", "clearance",
           "Clearance runs first: duplicate submissions, the broker's licence in every state where there's a location, and sanctions screening."),
         S("04", "SOV parsed and matched to last year", "view",
           "Every value is extracted with its exact cell. Matching against last year's schedule finds a building that was never on the expiring policy, and a warehouse that now describes battery storage."),
         S("06", "Pass 2 — rater and CAT model rerun on the renewal exposure", "reevaluate",
           "Now the rater and the cat model run three times, on controlled snapshots, so we can separate exposure growth, terms changes and pure rate."),
         S("03", "Appetite and triage", "view",
           "Appetite is fine: light manufacturing is in appetite. The problem isn't the class, it's price and terms."),
         S("05", "Underwriter accepts the material findings", "accept_findings",
           "The underwriter reviews and accepts the material findings. Every decision carries a reason code, so the carrier learns which rules are precise and which are noise."),
         S("08", "Quote near technical on guideline deductibles", "draft_quote",
           "We draft a quote near technical, and move the named-storm deductible to the floor the new guidelines require.", mode="suggested", terms="recommended"),
         S("07", "Refer — authority checked on the intended terms", "refer",
           "Authority is checked on the intended terms, not on the file. This one is above the underwriter's authority, so it's referred with a memo citing every piece of evidence."),
         S("07", "Approver signs off with a condition", "approve",
           "The approver signs off with a condition. That approval is locked to a hash of these exact terms; if anyone changes them, it's void.",
           conditions="Sprinkler inspection report within 30 days of bind"),
         S("09", "Quote sent to the broker", "send", "The quote goes to the broker."),
         S("09", "Broker responds", "broker_wait", "We move the clock forward to the broker's reply."),
         S("10", "Bind — authority re-checked, binder vs quote", "bind",
           "At bind, authority is re-checked on the bound terms, the approver's condition is printed on the binder as a subjectivity, and the binder is compared with the accepted quote."),
         S("11", "Policy system issues the policy", "issue",
           "Here's where most carriers lose control. The policy system keys one term incorrectly at issuance. Normally nobody sees this until a claim.", injection=True),
         S("11", "Corrective endorsement", "correct_issuance",
           "The platform caught it the same day. A corrective endorsement restates the bound term, the contract check re-runs, and the finding resolves."),
         S("10", "Broker sends the sprinkler inspection report", "data_request",
           "Finally, the outstanding subjectivity. We request the inspection report; the broker sends it, and it's matched to the subjectivity and cleared.",
           items=["Sprinkler inspection report"], wait=True),
         S("15", "Renewal file complete", "reevaluate",
           "The renewal file is complete: bound, issued, corrected, and every condition cleared."),
     ]},
    # ------------------------------------------------------------------------------------------------ S1
    {"id": "fast-track", "account_id": "acc_s1", "title": "Fast-track — no material change, confirm, quote, bind and issue",
     "aspects": ["Fast-track lane", "Flat RARC", "Clean issuance", "Billing"],
     "intro": "Not every renewal needs work. Crestline is an eight-building office portfolio. Watch how quickly the platform clears an account where nothing material has changed.",
     "outro": "Fast-tracking isn't skipping the checks. Every control ran; it just didn't find anything worth a human's time.",
     "brief": {
         "audience": "Underwriting operations, heads of underwriting, anyone who owns handling cost",
         "problem": "Underwriters spend the same effort on clean renewals as on problem ones, so the problem ones get less attention than they need.",
         "story": ["Renewal schedule arrives; all eight buildings match last year one-for-one.", "All controls run; nothing material is found.",
                   "The underwriter confirms the fast-track with one click; the quote is set at the exposure-adjusted expiring premium.",
                   "Broker accepts, the renewal is bound and issued exactly as bound, and billing is raised."],
         "watch": ["Stage 15: the fast-track confirmation", "Stage 06: adequacy above floor, RARC flat", "Stage 11: binder and policy agree; invoice raised"],
         "value": "Handling time on the clean part of the book (typically 40–50% of renewals) drops to minutes, with the same evidence trail.",
         "questions": ["What share of your renewals are genuinely no-change?", "How long does a no-change renewal take today?"]},
     "steps": [
         S("01", "Renewal schedule already received", "view", "The renewal schedule arrived in July, with values trended in line with construction-cost inflation."),
         S("02", "Clearance", "clearance", "Clearance passes."),
         S("04", "Extraction and matching", "view", "All eight buildings match last year's schedule one for one. No new locations, no occupancy changes, no conflicting evidence."),
         S("06", "Pricing — adequacy above floor", "view", "Technical price and adequacy are comfortably above the floor. There's nothing to fix."),
         S("15", "Underwriter confirms the fast-track", "confirm_maintain",
           "So the underwriter confirms the fast-track with one click. On a typical book, forty to fifty percent of renewals go down this lane."),
         S("08", "Quote at the expected premium on expiring terms", "draft_quote",
           "The quote is set at the exposure-adjusted expiring premium: a flat rate change, like for like.", mode="expected", terms="expiring"),
         S("09", "Sent to the broker", "send", "Sent to the broker."),
         S("09", "Broker responds", "broker_wait", "The broker replies."),
         S("10", "Bind", "bind", "Bound."),
         S("11", "Policy issued and billed", "issue", "Issued exactly as bound, and the premium is invoiced.", injection=False),
         S("15", "Contract check", "reevaluate", "The contract check confirms quote, binder and policy agree. Minutes of work, fully evidenced."),
     ]},
    # ------------------------------------------------------------------------------------------------ S10
    {"id": "decline-notice", "account_id": "acc_s10", "title": "Appetite decline — exception declined, statutory non-renewal notice",
     "aspects": ["Guideline change", "Notice deadline", "Non-renewal"],
     "intro": "Delta Scrap Metals is a long-standing account in a class the carrier has just decided to exit. This one is about acting on a guideline change in time.",
     "outro": "A guideline change only creates value if it reaches every affected account before the notice windows close.",
     "brief": {
         "audience": "CUO, compliance, portfolio management",
         "problem": "When appetite changes, affected renewals are found late; statutory notice windows are missed and the carrier is forced to renew business it wanted to exit.",
         "story": ["The 2026 guidelines decline scrap and recycling; the whole book is re-evaluated the day they publish.",
                   "The platform computes the latest valid notice date from the state notice table.",
                   "The underwriter asks for an exception; the CUO declines; the notice goes out inside the window."],
         "watch": ["Stage 03: the decline rule and the guideline version", "Stage 15: notice deadline countdown", "Mock outbox: the notice letter"],
         "value": "Every account affected by a guideline change is found immediately and actioned inside its statutory window.",
         "questions": ["When you last changed appetite, how long before every affected renewal was identified?"]},
     "steps": [
         S("03", "Guidelines 2026 decline this class", "view", "The 2026 guidelines decline scrap and recycling yards. The platform re-evaluated the whole book the day they were published."),
         S("15", "Statutory notice deadline", "view", "This is an admitted policy, so a non-renewal needs statutory notice. The platform works out the latest valid notice date and counts down to it."),
         S("07", "Underwriter requests an exception", "refer", "The underwriter asks for an exception on the strength of a long relationship. That goes to the chief underwriting officer.",
           note="Long-tenured account; request exception to renew one more term"),
         S("07", "CUO declines the exception", "decline", "The CUO declines. The class is outside appetite.", conditions="Class outside appetite; issue non-renewal"),
         S("15", "Non-renewal notice issued", "non_renew", "The non-renewal notice goes to the insured and the broker inside the statutory window, and it's logged against the account."),
         S("14", "Exposure leaves the portfolio", "view", "And the exposure leaves the portfolio view."),
     ]},
    # ------------------------------------------------------------------------------------------------ S7
    {"id": "midterm-event", "account_id": "acc_s7", "title": "Mid-term event — vacancy + sprinkler impairment, conditions, restoration verified",
     "aspects": ["In-force monitoring", "Event-driven evaluation", "Conditions", "Engineering visit"],
     "intro": "Renewal isn't the only moment that matters. Pinecrest Plaza is mid-term, and the risk has changed underneath the policy.",
     "outro": "That's in-force monitoring. The carrier finds out when the risk changes, acts, and verifies the fix — not when the loss happens.",
     "brief": {
         "audience": "Head of property, risk engineering, claims leadership",
         "problem": "Mid-term changes (vacancy, protection impairments) are recorded in separate systems and only reviewed at renewal, if at all.",
         "story": ["An endorsement records the anchor tenant leaving; then a sprinkler impairment notice arrives.",
                   "The platform re-evaluates immediately and raises a critical referral.",
                   "A senior underwriter approves continuation with conditions; the condition letter goes to the broker.",
                   "The broker returns the restoration certificate; an engineer visits and verifies it."],
         "watch": ["Stage 12: the event list and the event-driven re-evaluation", "Stage 05: the impairment recorded as verified evidence, then restored"],
         "value": "Deteriorating risks are acted on within days, with the fix verified, rather than discovered at renewal or after a loss.",
         "questions": ["How would an impairment notice reach the underwriter today?"]},
     "steps": [
         S("12", "In force: anchor tenant vacated", "view", "Earlier this year an endorsement recorded that the anchor tenant had left. Most of the centre is now vacant."),
         S("12", "Sprinkler impairment notice arrives", "advance_inforce", "Then a fire-protection impairment notice arrives: the sprinkler riser in the vacant unit has been shut off."),
         S("05", "Impairment recorded as verified evidence", "view", "That notice is recorded as verified evidence. Vacant and unsprinklered is one of the worst fire combinations there is."),
         S("07", "Critical referral raised mid-term", "refer", "The platform doesn't wait for renewal. A critical referral is raised the same day.", note="Majority vacant with sprinklers impaired"),
         S("07", "Continuation approved with conditions", "approve", "A senior underwriter approves continuation, subject to the sprinklers being restored and a fire watch.",
           conditions="Restore sprinklers and maintain fire watch within 7 days"),
         S("09", "Condition letter; broker returns the certificate", "data_request",
           "The condition letter goes to the insured through the broker. Three days later the broker returns the restoration certificate, and it's ingested as evidence.",
           items=["Sprinkler restoration certificate", "Fire watch log"], wait=True),
         S("05", "Engineer verifies the restoration on site", "order_survey",
           "Risk engineering visits to verify. The report is ingested as verified evidence.", scope="Impairment restoration verification", wait=True),
         S("15", "Account re-evaluated", "reevaluate", "And the account is re-evaluated on the verified facts."),
     ]},
    # ------------------------------------------------------------------------------------------------ S2 negotiation
    {"id": "counter-offer", "account_id": "acc_s2", "title": "Negotiation — broker counters, re-quote invalidates the approval",
     "aspects": ["Broker counter", "Terms-hash invalidation", "Re-approval"],
     "intro": "Negotiation is where discipline usually slips. Let's see what happens when the broker pushes back.",
     "outro": "Approvals attach to terms, not to accounts. That closes one of the most common authority gaps in commercial underwriting.",
     "brief": {
         "audience": "CUO, underwriting audit, delegated-authority managers",
         "problem": "A referral is approved at one price; the broker negotiates; a different price is bound on the strength of the original approval.",
         "story": ["The underwriter opens above technical; the quote is referred and approved.", "The broker counters.",
                   "The underwriter re-quotes at the counter and the original approval is invalidated automatically.",
                   "The new terms are re-referred and re-approved, then bound and issued."],
         "watch": ["Stage 07: status INVALIDATED on the first approval, with the reason", "Stage 09: the counter-offer in the mock outbox"],
         "value": "Every bound policy has an approval for exactly the terms bound.",
         "questions": ["Could you prove today that every bound policy was approved on its bound terms?"]},
     "steps": [
         S("01", "Broker submission arrives", "advance_submission", "The renewal submission arrives."),
         S("06", "Pricing rerun", "reevaluate", "Pricing is re-run on the new exposure."),
         S("08", "Opening quote above technical", "draft_quote", "The underwriter opens above technical.", mode="above_technical", terms="recommended"),
         S("07", "Refer", "refer", "It's referred."),
         S("07", "Approve", "approve", "And approved, on those exact terms."),
         S("09", "Send to broker", "send", "Sent to the broker."),
         S("09", "Broker counters", "broker_wait", "The broker comes back with a counter-offer."),
         S("08", "Re-quote at the counter — prior approval invalidated", "draft_quote",
           "The underwriter re-quotes at the counter. Watch the approval: because the terms changed, the earlier approval is invalidated automatically.", mode="counter", terms="recommended"),
         S("07", "Re-refer the new terms", "refer", "So the new terms have to be referred again."),
         S("07", "Re-approve", "approve", "Re-approved, against the new terms hash."),
         S("09", "Send", "send", "Sent."),
         S("09", "Broker responds", "broker_wait", "The broker replies."),
         S("10", "Bind", "bind", "Bound."),
         S("11", "Issue as bound", "issue", "And issued clean.", injection=False),
     ]},
    # ------------------------------------------------------------------------------------------------ S3
    {"id": "referral-declined", "account_id": "acc_s3", "title": "Referral declined — security evidence obtained, crime cover added, re-quoted and bound",
     "aspects": ["Declined referral", "Adequacy floor", "Broker documents", "Coverage gap"],
     "intro": "Lumen Jewelers has fourteen stores carrying high-value stock. This walkthrough shows the platform stopping an underpriced quote, getting the missing evidence, and closing a coverage gap.",
     "outro": "The platform doesn't replace the underwriter's judgement. It makes sure that judgement is exercised on the right facts, at the right authority.",
     "brief": {
         "audience": "Heads of underwriting, specialty/jewellers block owners",
         "problem": "Protective-safeguard warranties (monitored alarms) are assumed, not evidenced; under-priced quotes get through; coverage gaps like cash exposure are missed.",
         "story": ["Unmonitored alarms in high-crime stores breach the safeguard schedule; the broker said cash is kept on premises with no crime form.",
                   "An under-priced quote is referred and declined.", "The broker returns monitored-alarm certificates; the security findings clear on the evidence.",
                   "The re-quote adds the crime form, is approved, bound and issued."],
         "watch": ["Stage 05: safeguard findings before and after the certificates arrive", "Stage 07: the declined referral", "Stage 08: crime form on the quote"],
         "value": "Warranties are evidenced before bind, and coverage matches the exposure the broker disclosed.",
         "questions": ["How do you verify protective-safeguard warranties today?"]},
     "steps": [
         S("05", "Security findings: unmonitored alarms", "view", "Security first. Several stores in high-crime areas have alarms that aren't centrally monitored, even though the policy requires it."),
         S("06", "Pricing — technical vs expiring", "view", "Pricing compares the expiring premium with technical."),
         S("08", "Quote well below technical", "draft_quote", "The underwriter tries a quote well below technical.", mode="low", terms="expiring"),
         S("07", "Refer", "refer", "That's below the adequacy floor, so it needs a referral."),
         S("07", "Approver declines", "decline", "The approver declines: below adequacy, and the security evidence is missing.", conditions="Below adequacy floor; security evidence missing"),
         S("09", "Request alarm certificates; broker returns them", "data_request",
           "The underwriter asks the broker for monitored-alarm certificates. They arrive three days later, are parsed, and the security findings clear on the evidence.",
           items=["Monitored burglar alarm certificates for all stores"], wait=True),
         S("08", "Re-quote near technical with crime cover", "draft_quote",
           "The re-quote is near technical, and adds money-and-securities cover for the cash the broker disclosed.", mode="suggested", terms="recommended", add_forms=["NS-CR 01 00"]),
         S("07", "Refer again", "refer", "Referred again."),
         S("07", "Approved", "approve", "Approved."),
         S("09", "Send", "send", "Sent."),
         S("09", "Broker responds", "broker_wait", "The broker replies."),
         S("10", "Bind", "bind", "Bound."),
         S("11", "Issue", "issue", "Issued.", injection=False),
     ]},
    # ------------------------------------------------------------------------------------------------ S11
    {"id": "matching-dq", "account_id": "acc_s11", "title": "Data quality — renumbered campus, human-confirmed matches, priced and bound",
     "aspects": ["Location matching", "$000s scaling", "Human review", "Bind"],
     "intro": "Summit University's facilities team renumbered every building this year. For most systems, that breaks the year-over-year comparison entirely.",
     "outro": "If you can't match locations across years, every downstream comparison is noise. This is the foundation everything else sits on.",
     "brief": {
         "audience": "Data and operations leaders, anyone who has fought SOV quality",
         "problem": "SOVs arrive in inconsistent formats; renumbered or merged buildings break year-over-year comparison, so exposure change is guessed.",
         "story": ["The schedule is in thousands of dollars with a totals row and a hidden sheet; the parser fixes and logs each issue.",
                   "Most buildings match automatically; uncertain matches go to a human who confirms them.",
                   "Pricing runs on the matched exposure; the renewal is quoted, bound and issued."],
         "watch": ["Stage 04: parser corrections and the match method per building", "Data quality page: the review queue"],
         "value": "Reliable year-over-year exposure comparison, with a human only where the machine is unsure.",
         "questions": ["How much underwriter time goes into cleaning SOVs today?"]},
     "steps": [
         S("04", "SOV issues fixed; uncertain matches proposed", "view",
           "The schedule arrived in thousands of dollars, with a totals row and a hidden notes sheet. The parser scales values, drops the totals, and records each correction. Uncertain matches are proposed to a human."),
         S("04", "Underwriter confirms the proposed matches", "confirm_matches", "The underwriter confirms the proposed matches."),
         S("06", "Pricing rerun on matched exposure", "reevaluate", "Pricing is re-run on the matched exposure, including a new building and two halls merged in a renovation."),
         S("05", "Findings reviewed", "accept_findings", "The underwriter reviews the remaining findings."),
         S("08", "Quote", "draft_quote", "Quoted near technical.", mode="suggested", terms="expiring"),
         S("07", "Authority", "refer_if_needed", "Authority is checked; if the quote is above the underwriter's level it's referred and approved."),
         S("09", "Send", "send", "Sent."),
         S("09", "Broker responds", "broker_wait", "The broker replies."),
         S("10", "Bind", "bind", "Bound."),
         S("11", "Issue", "issue", "Issued as bound.", injection=False),
     ]},
    # ------------------------------------------------------------------------------------------------ S9
    {"id": "engineering-condition", "account_id": "acc_s9", "title": "Broken engineering commitment — evidence requested, verified on site, then bound",
     "aspects": ["Recommendation register", "Linked loss", "Engineering visit", "Conditions"],
     "intro": "Keystone Plastics shows what happens when an engineering commitment isn't kept, and how the platform gets it verified before the renewal binds.",
     "outro": "Engineering recommendations only reduce losses if someone checks they were done. Here that check is part of the workflow.",
     "brief": {
         "audience": "Risk engineering, head of property, claims",
         "problem": "Engineering recommendations are marked closed without evidence; losses then occur on exactly the hazard that was meant to be fixed.",
         "story": ["A bind-condition recommendation was closed with no evidence; a large fire then started in that same equipment.",
                   "The broker sends a contractor's completion certificate; it's recorded but not yet verified.",
                   "An engineer visits and verifies the work on site; the recommendation becomes verified closed.",
                   "The renewal is quoted, referred, approved and bound."],
         "watch": ["Stage 05: the recommendation status moving OPEN → CLOSED (evidence) → VERIFIED_CLOSED (site visit)", "Stage 13: the claim linked to the recommendation"],
         "value": "Critical recommendations are verified, not assumed, before the carrier renews.",
         "questions": ["What share of your 'closed' recommendations have completion evidence?"]},
     "steps": [
         S("05", "Bind-condition recommendation closed without evidence", "view", "Last year, spark detection on a dust collector was a condition of binding. The register shows it closed, but with no completion evidence."),
         S("13", "Large fire linked to the open recommendation", "view", "Then a large fire started in that same dust collector. The platform links the claim to the recommendation."),
         S("05", "Underwriter accepts the engineering findings", "accept_findings", "The underwriter accepts the engineering findings."),
         S("09", "Broker returns the completion certificate", "data_request",
           "A request goes to the broker for completion evidence. The contractor's certificate comes back and is attached, but it isn't verified yet.",
           items=["Contractor completion certificate for R-0412 (spark detection and explosion venting)"], wait=True),
         S("05", "Engineer verifies the work on site", "order_survey", "So risk engineering visits. The report verifies the work, and the recommendation is closed as verified.",
           scope="Verification of R-0412 completion", wait=True),
         S("08", "Quote near technical", "draft_quote", "The renewal is quoted near technical.", mode="suggested", terms="expiring"),
         S("07", "Refer", "refer", "Referred, because of the linked loss."),
         S("07", "Approve", "approve", "Approved, with the verification on file."),
         S("09", "Send", "send", "Sent."),
         S("09", "Broker responds", "broker_wait", "The broker replies."),
         S("10", "Bind", "bind", "Bound."),
         S("11", "Issue", "issue", "Issued.", injection=False),
     ]},
    # ------------------------------------------------------------------------------------------------ S8
    {"id": "contract-authority", "account_id": "acc_s8", "title": "Contract integrity & authority — prior-term breaches, subjectivity cleared, error corrected",
     "aspects": ["Invalidated approval", "Lost NS minimum", "Subjectivity", "Corrective endorsement"],
     "intro": "St. Aurelia is a hospital campus. Its problems started last year, in the contract itself.",
     "outro": "Contract integrity is the cheapest control to run, and one of the most expensive to skip.",
     "brief": {
         "audience": "CUO, underwriting audit, policy operations",
         "problem": "Terms change between quote, binder and policy without anyone noticing; approvals don't match what was bound; subjectivities stay open indefinitely.",
         "story": ["Prior term: the named-storm minimum was dropped on the issued policy, and the approval covered a different quote version than the one bound.",
                   "At renewal the account is quoted on guideline terms, referred and approved with a subjectivity.",
                   "The policy system drops the minimum again; it is caught the same day and corrected by endorsement.",
                   "The broker sends the generator load test and the subjectivity clears."],
         "watch": ["Account → Contract tab: the prior-term diff", "Stage 07: approval vs bound version", "Stage 11: corrective endorsement"],
         "value": "Every issued policy matches what was approved and bound, and conditions are closed out.",
         "questions": ["How often does your audit find binder/policy mismatches, and how long after issuance?"]},
     "steps": [
         S("11", "Prior term: named-storm minimum missing on the policy", "view", "On the expiring policy, the named-storm minimum from the binder never made it onto the issued policy."),
         S("07", "Prior term: approval covered a different version", "view", "And the referral approved one version of the quote, while a later version with a lower minimum was bound."),
         S("01", "Renewal submission arrives", "advance_submission", "The renewal submission arrives."),
         S("06", "Pricing rerun", "reevaluate", "Pricing is re-run."),
         S("08", "Quote on guideline terms", "draft_quote", "The renewal is quoted on guideline terms.", mode="suggested", terms="recommended"),
         S("07", "Refer", "refer", "Referred."),
         S("07", "Approve with a subjectivity", "approve", "Approved, subject to the generator load test that was still outstanding.", conditions="Generator load test report within 30 days of bind"),
         S("09", "Send", "send", "Sent."),
         S("09", "Broker responds", "broker_wait", "The broker replies."),
         S("10", "Bind", "bind", "Bound, with the load test printed on the binder as a subjectivity."),
         S("11", "Policy system drops the minimum again", "issue", "And the policy system drops the named-storm minimum again at issuance.", injection=True),
         S("11", "Caught and corrected by endorsement", "correct_issuance", "This time it's caught the same day and corrected by endorsement."),
         S("10", "Broker sends the generator load test", "data_request", "The broker sends the load test report, and the subjectivity clears.", items=["Generator load test report"], wait=True),
         S("15", "Renewal file complete", "reevaluate", "The file is complete."),
     ]},
    # ------------------------------------------------------------------------------------------------ S6 (new)
    {"id": "clearance-hold", "account_id": "acc_s6", "title": "Clearance hold — expired broker licence blocks quoting until resolved",
     "aspects": ["Clearance", "Licence by state", "Broker documents", "Cooking safeguards"],
     "intro": "Ember and Oak is a restaurant group across eight states. Before any pricing, the platform checks that the carrier can legally accept this business from this broker.",
     "outro": "Compliance is a gate, not a report. Nothing was quoted until the broker was licensed in every state on the schedule.",
     "brief": {
         "audience": "Compliance, distribution management, underwriting operations",
         "problem": "Broker licences are checked at appointment, not per submission and per location state; business is quoted through brokers who aren't licensed where the risk is.",
         "story": ["Clearance finds the broker's licence expired in one location state; the account goes on hold and quoting is blocked.",
                   "The underwriter requests the renewed licence and the kitchen hood cleaning certificates.",
                   "The broker returns both; clearance re-screens and passes; the cooking findings clear on the certificates.",
                   "The renewal is quoted, bound and issued."],
         "watch": ["Stage 02: HOLD and the reason", "Stage 08: quote attempt refused", "Stage 05: cooking findings clearing after the certificates arrive"],
         "value": "No quote leaves the building unless the carrier can legally write it.",
         "questions": ["Is licence checked per location state on your multi-state renewals today?"]},
     "steps": [
         S("02", "Clearance — licence expired in one state", "clearance", "Clearance checks the broker's licence in every state where there's a location. One of them has expired, so the account is on hold."),
         S("08", "Quote attempt is blocked", "try_quote", "If the underwriter tries to quote anyway, the platform refuses. It's a gate, not a warning."),
         S("09", "Request licence and hood certificates; broker returns them", "data_request",
           "The underwriter asks the broker for the renewed licence, and for the kitchen hood cleaning certificates the cooking findings need. Both arrive three days later and are parsed.",
           items=["Renewed producer licence", "Kitchen hood cleaning certificates"], wait=True),
         S("02", "Clearance re-screened", "clearance", "Clearance re-screens automatically, and passes."),
         S("05", "Cooking safeguard findings cleared", "view", "And the cooking suppression findings have cleared on the certificates."),
         S("05", "Underwriter reviews remaining findings", "accept_findings", "The underwriter reviews what's left."),
         S("08", "Quote", "draft_quote", "Now the renewal can be quoted.", mode="suggested", terms="expiring"),
         S("07", "Authority", "refer_if_needed", "Authority is checked, and referred if needed."),
         S("09", "Send", "send", "Sent."),
         S("09", "Broker responds", "broker_wait", "The broker replies."),
         S("10", "Bind", "bind", "Bound."),
         S("11", "Issue", "issue", "Issued.", injection=False),
     ]},
    # ------------------------------------------------------------------------------------------------ S4 (new)
    {"id": "occupancy-survey", "account_id": "acc_s4", "title": "Occupancy drift — battery storage found, engineer confirms, renewal conditioned",
     "aspects": ["Occupancy drift", "Imagery", "Engineering visit", "New recommendation", "Conditions"],
     "intro": "Redline Logistics runs three distribution centres. The broker mentioned a new contract in passing. The platform worked out what it means for the fire risk.",
     "outro": "The broker's email, the imagery and the engineer's visit told one story. The renewal is priced and conditioned on it.",
     "brief": {
         "audience": "Head of property, risk engineering, pricing",
         "problem": "Occupancy changes are disclosed informally (an email line) and never reach the rating or the sprinkler adequacy check.",
         "story": ["The broker's email says lithium-ion batteries are now stored in new high-bay racks; imagery shows new racking.",
                   "Storage height exceeds the sprinkler design; a verification survey is ordered.",
                   "The engineer confirms and raises a critical recommendation.",
                   "The renewal is quoted at technical with a condition to fix the protection, referred, approved, bound and issued."],
         "watch": ["Account → Documents: the email highlight that created the occupancy observation", "Stage 05: the new critical recommendation", "Stage 10: the condition as a subjectivity"],
         "value": "Material occupancy changes are captured from unstructured disclosure and acted on before the renewal binds.",
         "questions": ["Where would a one-line occupancy change in a broker email get picked up today?"]},
     "steps": [
         S("01", "Broker email mentions battery storage", "view", "The broker's email mentions, in passing, a new contract storing e-bike batteries at the Dallas facility. That sentence is captured as evidence."),
         S("04", "Imagery and SOV confirm new racking", "view", "Imagery shows new high-bay racking, and the schedule shows the stock value up sharply."),
         S("05", "Storage exceeds sprinkler design — survey ordered", "order_survey",
           "Storage now exceeds the sprinkler design height. The underwriter orders a verification survey; the engineer visits a week later.", scope="Occupancy change and sprinkler adequacy", wait=True),
         S("05", "Engineer raises a critical recommendation", "view", "The engineer confirms the storage and raises a critical recommendation: in-rack sprinklers, or reduce storage height."),
         S("05", "Underwriter accepts the findings", "accept_findings", "The underwriter accepts the findings."),
         S("08", "Quote at technical", "draft_quote", "The renewal is quoted at technical on the verified occupancy.", mode="technical", terms="expiring"),
         S("07", "Refer", "refer", "Authority is checked on the intended terms, and the quote is referred."),
         S("07", "Approved with a protection condition", "approve", "It's approved, conditional on the protection being fixed.", conditions="In-rack sprinklers installed or storage reduced to within design within 60 days"),
         S("09", "Send", "send", "Sent."),
         S("09", "Broker responds", "broker_wait", "The broker replies."),
         S("10", "Bind with subjectivity", "bind", "Bound, with the protection condition printed as a subjectivity."),
         S("11", "Issue", "issue", "Issued.", injection=False),
     ]},
]
